### ISSUE TITLE
Document with mathematical notation the geometric model used by Blender 

### ISSUE THREAD

**Issue by traversaro** [robotology/blender-robotics-utils#3]
In https://github.com/robotology/blender-robotics-utils/blob/master/script/urdfToBlender.py we have a URDF --> Blender rig converter that is working fine on some URDF model, but creating problems on some other models. However, debugging the problem is tricky as we do not have a clear mathematical definition and/or understanding of how the Blender Armature system  ( https://docs.blender.org/manual/en/latest/animation/armatures/structure.html#chains-of-bones ) works. In this issue we will document this with mathematical notation, so it will simplify future mantainance of the software.

Unless noted otherwise, the notation used for expressing homegenous transforms is the one defined in https://research.tue.nl/en/publications/multibody-dynamics-notation-version-2, and as LaTeX formulas will be used in the issue, please install an appropriate plugin such as https://chrome.google.com/webstore/detail/mathjax-plugin-for-github/ioemnmodlmafdkllaclgeombjnmnbima?hl=en for Chrome or https://addons.mozilla.org/en-US/firefox/addon/green-pi/ for Firefox to visualize them in the browser.

cc @Nicogene

**Comment by traversaro** [comment]
In today's meeting, we sorted out most of the doubts, and I will provide a recap soon. The only doubt was the semantics of the roll w.r.t. to how the X and Z direction of the bone are oriented, but w.r.t. to that the `bpy.types.Bone.MatrixFromAxisRoll` method (see https://docs.blender.org/api/current/bpy.types.Bone.html?highlight=bone#bpy.types.Bone.MatrixFromAxisRoll) should provide all the information. By digging in the code, the underlying implementation of that method seems to be https://github.com/blender/blender/blob/594f47ecd2d5367ca936cf6fc6ec8168c2b360d0/source/blender/blenkernel/intern/armature.c#L2155 .

**Comment by traversaro** [comment]
> 
> 
> In today's meeting, we sorted out most of the doubts, and I will provide a recap soon. The only doubt was the semantics of the roll w.r.t. to how the X and Z direction of the bone are oriented, but w.r.t. to that the `bpy.types.Bone.MatrixFromAxisRoll` method (see https://docs.blender.org/api/current/bpy.types.Bone.html?highlight=bone#bpy.types.Bone.MatrixFromAxisRoll) should provide all the information. By digging in the code, the underlying implementation of that method seems to be https://github.com/blender/blender/blob/594f47ecd2d5367ca936cf6fc6ec8168c2b360d0/source/blender/blenkernel/intern/armature.c#L2155 .

Related SO questions:
* https://blender.stackexchange.com/questions/165742/using-python-how-do-you-get-the-roll-of-a-pose-bone
* https://blender.stackexchange.com/questions/222968/how-is-the-bone-matrix-axis-orientation-roll-defined

**Comment by traversaro** [comment]
## Recap Blender Bone Formalism 

This is based on https://docs.blender.org/manual/en/latest/animation/armatures/introduction.html and the meeting that we had with @Nicogene and @xEnVrE .

In Blender, the basic unit of the kinematic structure is the bone, that is a rough equivalent of a link in URDF.

Each bone rest position is defined by three parameters:
* ${}^W h \in \mathbb{R}^3$ : the head, a point in the 3D space expressed in the WORLD reference frame 
* ${}^W t \in \mathbb{R}^3$ : the tail, a point in the 3D space expressed in the WORLD reference frame.
* $r \in \mathbb{R}$: the roll

To each bone it correspond a frame, whose origin is centered in the head, whose Y direction is specified by the vector ${}^W t - {}^W h$ (and this is the reason why the head and tail cannot be coincident) and the roll specify in some way the X and Z direction in the plane ortoghonal to Y (with the logic implemented in https://github.com/blender/blender/blob/594f47ecd2d5367ca936cf6fc6ec8168c2b360d0/source/blender/blenkernel/intern/armature.c#L2155, that however I did not investigated). 

Something that is work stressing is that the position of the tail does not play any role in defining the position of any child of the bone. The rest position of any bone is always expessed with head, tail and roll w.r.t. to the world frame of simulation, and the tail position of its parent is not related at all to it.

So, let's say that that we have two bones, $P$ (parent) and $C$ (child). Their rest positions in the world frame $W$ are defined as:
$$
{}^W H_{P_0} = H({}^W h_P, {}^W t_P, r_P)
$$

$$
{}^W H_{C_0} = H({}^W h_C, {}^W t_C, r_C)
$$

The rotational motions that can be constrainted for a child bone w.r.t. to its parent bone are the main one of the axis aligned with the child bone: so if we want to permit a rotational motion around an arbitrary axis, we need to make sure that one direction of the bone frame is aligned with the axis. The converter in blender-robotics-utils ensures that by always choosing the head and tail of the bone to be aligned with the axis specified in the URDF. So assuming that you have a model that only allows a rotation around the Y direction (as the one generated by the converter), the relative transformation between P and C is given by:
$$
{}^P H_{C} = {}^{P_0} H_{C_0} AxisAngle( {}^{C_0} R_W normalize({}^W t_C-{}^W h_C), q_J)
$$

where $ {}^{P_0} H_{C_0}$ is computed as:
$$
 {}^{P_0} H_{C_0} = {}^W H_{P_0}^{-1} {}^W H_{C_0}
$$

**Comment by traversaro** [comment]
I personally understood much more after our discussion. It would be nice to introduce some of this formalism in the docs, but if we want to do this we just need to get it from here, so I think we can close the issue now.

**Comment by Nicogene** [comment]
> It would be nice to introduce some of this formalism in the docs

I completely agree with that, we should find a way to publish it without requiring addons to be installed in the browser if possible
